package com.adonis.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PersonDesign extends HorizontalLayout {
    protected Image picture;
    protected TextField firstName;
    protected TextField lastName;
    protected TextField email;
//    protected DateField dateOfBirth;
    protected TextArea notes;
    protected TextField login;
    protected PasswordField password;
    protected Button save;
    protected Button cancel;
    protected Button delete;

    public PersonDesign() {
		Design.read(this);
	}
}
